app/views/layouts/application.html.erb

#7 
**対応内容**
- 標準的なDBCLS用共通ヘッダの導入しました。
　https://github.com/dbcls/website/tree/master/DBCLS-common-header-footer/v2
**確認確認**
- 画面起動でヘッダーにDBCLS用共通ヘッダが表示されること
**画面**
を
に変更しました。

issue #7 DBCLS共通ヘッダーの挿入

---

app/views/dictionaries/_dictionary_selection.html.erb
app/views/dictionaries/_selected_dictionary.html.erb
app/views/dictionaries/_unselected_dictionary.html.erb

When the name of the dictionary contains a space, there is a problem that the dictionary cannot be selected in Find IDs and Annotation, so fix it.
- Added processing to convert spaces to caret("^") when generating the ID of the HTML element of the dictionary
- Changed so that the ID containing the caret can also be specified in the Jquery selector

Fixed a bug that the dictionary cannot be selected when the dictionary name contains spaces

---

app/controllers/dictionaries_controller.rb

Fixed code deprecated in Rails 6.0.3.
- Revised `update_attributes` to `update`
- `update_attributes` will be removed in Rails 6.1

Revised DEPRECATION WARNING in Rails 6.0.3

---

Gemfile
Gemfile.lock

Fixed a problem that the error was not displayed properly in the development environment due to the version of web-console.
- update web-console to 4.1.0

Update web console gem

---

app/controllers/annotation_controller.rb
app/lib/text_annotator/annotation_queue_overflow_error.rb

Due to the effect of upgrading to Rails6, Zeitwerk :: NameError is now displayed when running `rails s` in the production environment. Fix `app/lib /text_annotator/annotation_queue_overflow_error.rb`.
- Nested AnnotationQueueOverflowError class with TextAnnotator class

Fix Zeitwerk::NameError in production environment

---

app/jobs/application_job.rb

In ActiveJob, after_perform callback is not called when the job fails, and message and ended_at are not saved in the Job record.
Revise to save message and ended_at in Job record even when job fails.
- Revised to update Job record in rescue_from

Fix bug that message is not saved in job record

---

Gemfile
Gemfile.lock
app/jobs/application_job.rb
app/jobs/text_annotation_job.rb
app/models/job.rb
db/migrate/20210309025257_add_queue_name_column_to_jobs.rb
db/schema.rb

Add activejob-cancel to remove the dependency on DelayedJob from the `destroy_if_not_running` method of `job.rb`.
- Added activejob-cancel gem
- https://github.com/y-yagi/activejob-cancel
- Added queue_name column to jobs table
- Because to identify the waiting job to be deleted by activejob-cancel
- Removed dependency on DelayedJob from destroy_if_not_running method

Add activejob-cancel to remove dependency on DelayedJob

---

app/jobs/application_job.rb
app/jobs/text_annotation_job.rb
app/models/job.rb
config/initializers/delayed_job_config.rb
db/migrate/20210309061752_remove_delayed_job_id_column_to_jobs.rb
db/schema.rb

Revise the code that depends on DelayedJob to make it easier to migrate background jobs.
- Removed settings to leave failed delayed_jobs
- Removed delayed_job_id column to jobs table
- Revised code that depends on DelayedJob
- Dependencies in the job management screen have not been removed

Remove dependencies on delayed job

---

app/controllers/annotation_controller.rb
config/routes.rb

Remove annotation_job method in annotation_controller.rb because it is not used.
- Remove annotation_job method and route

Remove annotation job method in annotation_controller.rb

---

app/views/jobs/index.html.erb

Since the delayed_job_id column has been removed from the jobs table, the delayed_job_id column is also removed from the job management view.
- Remove delayed_job_id column from `app/views/jobs/index.html.erb`

Remove delayed_job_id column from job management view

---

app/jobs/load_entries_from_file_job.rb

Revised the progress management of LoadEntriesFromFileJob to update num_dones when `new_entries.length >= transaction_size` is false.
- Revised to update num_dones when `new_entries.length >= transaction_size` is false

Fix LoadEntriesFromFileJob's progress management

---

docker-compose.yml
elasticsearch/Dockerfile

appleシリコンの環境でdocker開発環境を起動するための対策を実施しましたので、ご確認よろしくお願いいたします。
- 各コンテナのプラットフォームを`linux/amd64`に指定
- `elasticsearch `を7系の最新に更新
- `discovery.type=single-node`を設定してbootstrap checksでエラーになってしまうのを回避
- https://github.com/elastic/elasticsearch/issues/69767
- https://hub.docker.com/_/elasticsearch/tags
- https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html

appleシリコン用対策

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
app/views/layouts/application.html.erb

#55 
EntriesテーブルへのTagカラム追加(select2導入とビューだけ)が完了しました。
ビューイメージも含め、認識違いがないか、ご確認よろしくお願いします。
- dictionary#showページのEntriesテーブルにタグ列を追加
- select2を導入し、entity登録行でそのdictionaryにつけられているタグを複数選択可能なところまで実装
- entityの登録時にタグを紐づけるロジックは未実装
- 上記のため、entity作成後のtag表示やsearch機能は未実装
実装前
実装後
[![Image from Gyazo](https://i.gyazo.com/fcb78ed6b71a2033bdd9a88129e9523b.gif)](https://gyazo.com/fcb78ed6b71a2033bdd9a88129e9523b)

EntriesテーブルにTagカラムを追加

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/entries.scss
app/controllers/entries_controller.rb
app/models/entry.rb
app/views/entries/_entry.html.erb
db/migrate/20240226041211_add_cascade_delete_to_entry_tags.rb
db/schema.rb

close #55 
EntryへのTag登録が完了しましたので、ご確認よろしくお願いいたします。
- 前PRにて作ったselect2のフォームで、そのdictionaryに紐づいているtagを選択出来るようにし、＋ボタンクリックで選択したtagをentry-tagsテーブルにて紐づけ保存できるようにする
- タグは複数選択可能で、選択取りやめも可能
- 作成後のentryを削除するときに、entry-tagの紐づけも削除する
- tag列を追加したことによって、表のバランスが悪くなったので、label列のwidth設定を60%→50%に狭めさせていただきました。
- 選択取りやめを実装するために`allowClear: true`を設定した場合にエラーになるバグがあるため、`placeholder`を空欄で設定しました。
参考：https://github.com/select2/select2/issues/3497#issuecomment-124122158
https://github.com/pubannotation/pubdictionaries/assets/149556430/d9b64702-22b8-41d8-80e0-1492440ac5f1

EntryにTagを登録

---

app/helpers/dictionaries_helper.rb
app/helpers/users_helper.rb
app/views/dictionaries/show_patterns.html.erb
app/views/entries/_entry.html.erb
app/views/patterns/_pattern.html.erb

close #63
font-awesome-sassのアイコン修正が完了しましたので、ご確認よろしくお願いいたします。
- font-awesome-sass gemを使用しているアイコンが、問題なく表示出来ているか確認
　　→googleマーク1件、trash-boxマーク4件が表示できていなかった([結果詳細](https://github.com/pubannotation/pubdictionaries/issues/63#issuecomment-1963657081))
- 現在のバージョンに適合した記述に修正
- login画面のgoogleマーク(現在コメントアウトされているが、念の為修正し、一時的にコメントを解除して確認しました)
修正前
修正後
- trash-boxマーク
dictionary詳細画面
pattern画面

font-awesome-sassのアイコン修正

---

app/controllers/dictionaries_controller.rb
app/models/dictionary.rb
app/models/tag.rb

close #60 
使用中のTagを削除できなくするタスクが完了しましたので、ご確認よろしくお願いいたします。
- dictionary#update時にtagを削除し、updateボタンを押した際、そのtagが使用されているときはエラーを表示して、タグは更新されないようにする
https://github.com/pubannotation/pubdictionaries/assets/149556430/d0490d74-996e-4e54-8b48-0aeb5d6e58c2

使用中のTagを削除できなくする

---

app/controllers/dictionaries_controller.rb
app/models/dictionary.rb
app/models/entry.rb
app/views/dictionaries/_counts.erb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
config/locales/en.yml

close #65 
Entry::MODE_AUTO_EXPANDED追加が完了しましたので、ご確認よろしくお願いいたします。
- Entry::MODEに`Entry::MODE_AUTO_EXPANDED`を追加
- モード追加に伴い、モードごとで条件わけしている場面などに`Entry::MODE_AUTO_EXPANDED`の場合の分岐を追加
- 仮で、Dictionary詳細画面右上のモード別entryカウントのビュー表示を追加
- 各モードのタイトルにカーソルを合わせると表示される説明書きは、詳細不明のため未記載(config/locales/en.yml)
- `# モード`をクリックすると、そのモードのentryが表に表示されるが、その表示条件や削除、モード遷移条件など不明のため、一旦仮で記載しているが修正が必要(app/views/entries/_entry.html.erb)
https://github.com/pubannotation/pubdictionaries/assets/149556430/50b964c1-c506-4616-86f1-cf956a5e4494

Entry::MODE_AUTO_EXPANDED追加

---

app/assets/stylesheets/entries.scss
app/models/entry.rb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
db/migrate/20240301042744_add_score_to_entries.rb
db/schema.rb
db/seeds.rb

close #69 
Entryへのscoreカラム追加が完了しましたので、ご確認よろしくお願いいたします。
- Entryテーブルへscoreカラムを追加(任意、0以上1未満、小数点以下4位まで許容)
- seedデータの方も、Entry::MODE_AUTO_EXPANDEDモードのentryにはscoreを追加設定
- 一旦登録したscoreが見れるように、`#Auto Expanded`での絞り込みページにscoreを表示する列を追加
- scoreはユーザーが直接入力しない認識なので、入力フォームは作っていません
- 現在、`#Auto Expanded`での絞り込みページ以外にはscore列は見れないようにしています。必要であれば次issueで対応いたします。

Entryへのscoreカラム追加

---

app/controllers/entries_controller.rb
app/helpers/dictionaries_helper.rb
app/models/dictionary.rb
app/models/entry.rb
app/views/entries/_colgroup.erb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
config/routes.rb

close #77 
Dictionary詳細画面の改修が完了しましたので、ご確認よろしくお願いいたします。
- Grayモード→Blackモードへのモード切替を`switch_to_black`というメソッド名に変更（動作は同じ）
- Auto expendedモードの絞り込み画面では、Scoreの降順で表示するように設定
- Auto expendedモードの絞り込み画面にて、チェックボックスを設置し、ゴミ箱マークを押下したら、チェックされているentryを削除(blackでもなく、DBから完全削除)、削除前にアラートで確認
- 右上の#Auto expandedのゴミ箱マークをクリックしたら、Auto expandedモードのentryを全削除する
- Auto expendedモードは現状entries_numに含まれていないため、削除などをしても値のインクリメント等の動作はいれていない。必要があればentries_num自体の見直しの際に対応する予定。
Gray→Blackへのモード切替
https://github.com/pubannotation/pubdictionaries/assets/149556430/cbc7410c-57e1-46de-ae30-441873bedf96
Auto expandedのチェックボックスからの削除
https://github.com/pubannotation/pubdictionaries/assets/149556430/22eaef8e-b164-49fc-a679-3241c38e757c
Auto expandedの全削除
https://github.com/pubannotation/pubdictionaries/assets/149556430/6ce3e1d9-7b7b-46ef-b8a0-d2 …

Dictionary詳細画面の改修

---

app/controllers/dictionaries_controller.rb
app/controllers/entries_controller.rb
app/helpers/dictionaries_helper.rb
app/jobs/load_entries_from_file_job.rb
app/models/dictionary.rb
app/models/entry.rb
app/models/entry_mode.rb
app/views/dictionaries/_counts.erb
app/views/dictionaries/show_patterns.html.erb
app/views/entries/_entry.html.erb
db/seeds.rb

#83 
EntryModeクラス作成が完了しましたので、ご確認よろしくお願いいたします。
- EntryModeモデルを作成し、Entryモデルで定義していたentry.modeの定数定義などを移動させた
- 上記変更に伴い、定数名を変更し、使用している箇所も修正
- `entry.mode_to_s`で文字列に変換するメソッドについて、EntryModeモデルで実施するように変更(前PRでコメントいただいていた箇所)
- 動作確認し、変更前と同じ挙動になることを確認
- Mode情報を使用しているEntryモデル内のメソッドは他にもありますが、一旦定数名を変更するだけの対応とし、EntryModeモデルへ移管したりはしていません。その必要があるものがあれば、追加で対応します。
https://github.com/pubannotation/pubdictionaries/assets/149556430/fb01d82b-5d3b-494e-a6e0-c9e1e97ba80f

EntryModeクラス作成

---

app/models/dictionary.rb

close #80 
Dictionary#expand_synonymメソッドの実装が完了しましたので、ご確認よろしくお願いいたします。
- issue記載の仕様通りに動作するよう、`expand_synonym`メソッドを作成
- `synonym_expansion`メソッドの返り値は、`label`と`score`を含むハッシュ配列と仮定して実装
- 動作確認は次issueで実施の認識です
- 例外処理などはまだ考慮できていません
- `synonym_expansion`メソッドは中身未実装

Dictionary#expand_synonymメソッドを実装

---

app/models/dictionary.rb
app/views/entries/_entry.html.erb

close #81 
synonym_expansionメソッドのダミー実装が完了しましたので、ご確認よろしくお願いいたします。
- 前issueの`expand_synonym`メソッドにおいて、Blackモードのentryは除外するように追加実装
- `synonym_expansion`メソッドをダミーで実装(issueの通り)
- 一回手動で関数実行してみて、問題なく動作することを確認
- Auto expandedに関数実行後のentryが格納されている
- IDで絞り込みをしたとき、Black以外のモードのentryがダミーlabelで複製(拡張)されて保存されている
https://github.com/pubannotation/pubdictionaries/assets/149556430/11aead36-645d-4b20-ab70-9c87a53b1d88

synonym_expansionメソッドのダミー実装

---

app/controllers/dictionaries_controller.rb
app/controllers/expand_synonym_jobs_controller.rb
app/jobs/expand_synonym_job.rb
config/routes.rb

close #82 
ExpandSynonymJobの実装が完了しましたので、ご確認よろしくお願いいたします。
- ExpandSynonymJobを作成し、`expand_synonym`を実行するように設定
- `DitionaryController#expand_synonym`を作成し、`compile`を参考にJobを実行するよう実装
- `DitionaryController#expand_synonym`をルーティング(compileはGETでしたが、entryの作成が含まれるためPOSTにしました)
- このアクションをトリガーするボタンの作成などは次issueで実施

ExpandSynonymJobの実装

---

app/views/dictionaries/_expand_synonym.html.erb
app/views/dictionaries/edit.html.erb

close #85 
dictionary編集へのexpand_synonym機能追加が完了しましたので、ご確認よろしくお願いいたします。
- Dictionary編集画面の一番下にexpand_synonymの実行ボタンを追加し、ボタン押下で`ExpandSynonymJobsController#create`が実行されるようにする
- 手動で実行できていることを確認
各種文言は指示になかったので、校正していただけますと幸いです。
https://github.com/pubannotation/pubdictionaries/assets/149556430/0925a019-7c82-4ccf-89e6-f41ddd7b9be8

dictionary編集にexpand_synonym機能追加

---

app/controllers/entries_controller.rb
app/models/dictionary.rb
app/views/entries/_colgroup.erb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
config/routes.rb

close #84 
auto_expandのentryをwhiteに確定する機能の追加が完了しましたので、ご確認よろしくお願いいたします。
- Dictionary詳細画面のAuto expanded絞り込み画面において、Scoreの右列にWhiteモードへの確定ボタンを設置
- ボタンを押したら、そのentryはWhiteモードに切り替わるように設定
- 切り替わりに伴い、右上のカウンターが変動し、切り替えたentryはWhiteの画面に表示されるようにする
- 手動で動作に問題ないことを確認
https://github.com/pubannotation/pubdictionaries/assets/149556430/c1e8ed9b-7988-4a1c-bef7-2af8ae99cd36

auto_expandのentryをwhiteに確定する機能の追加

---

app/controllers/dictionaries_controller.rb
app/controllers/lookup_controller.rb
app/models/dictionary.rb

close #96 
Dictionary詳細画面のN+1問題対応が完了しましたので、ご確認よろしくお願いいたします。
- Entry-Tagsの部分がN+1問題を起こしていたので、Entries読み込みの際にincludes(:tags)で読み込んでおくことで対応した
スクショのように7つのデータを読み込んで表示する部分で、修正前後のログを確認
- 修正前
```
[1m[36mTag Pluck (0.1ms)[0m  [1m[34mSELECT "tags"."value", "tags"."id" FROM "tags" WHERE "tags"."dictionary_id" = $1[0m  [["dictionary_id", 23]]
↳ app/views/entries/_table.html.erb:58
Rendered entries/_colgroup.erb (Duration: 0.0ms | Allocations: 12)
[1m[36mTag Load (0.9ms)[0m  [1m[34mSELECT "tags".* FROM "tags" INNER JOIN "entry_tags" ON "tags"."id" = "entry_tags"."tag_id" WHERE "entry_tags"."entry_id" = $1[0m  [["entry_id", 92946]]
↳ app/views/entries/_entry.html.erb:30
[1m[36mTag Load (0.2ms)[0m  [1m[34mSELECT "tags".* FROM "tags" INNER JOIN "entry_tags" ON "tags"."id" = …
```

Dictionary詳細画面のN+1問題対応

---

app/controllers/dictionaries_controller.rb
app/controllers/lookup_controller.rb
app/models/dictionary.rb
app/models/entry.rb
db/seeds.rb

close #100 
絞り込みメソッドのscope化が完了しましたので、ご確認よろしくお願いいたします。
- Dictionary詳細画面におけるlabel, identifier, tagの絞り込み処理をscope化し、`entries_with_tags = @dictionary.entries.includes(:tags)`と接続するため、Entryモデルに移動させた
- Dictionaryモデルに定義していたメソッドのうち、
- labelのみ別の箇所で使用していたので、前PRで修正する前の状態に戻した
- identifier, tagは使用しなくなったので削除
- Dictionary#showでの記述をscopeに合わせて修正
- labelの検索テストが出来なかったため、seedファイルでnorm1カラムを追加
https://github.com/pubannotation/pubdictionaries/assets/149556430/7e6db34a-0200-4d44-a223-5f36a8d0941b

絞り込みメソッドをscope化

---

app/controllers/lookup_controller.rb
app/models/dictionary.rb
app/models/entry.rb

close #103
絞り込みメソッドをscope化(lookup)が完了しましたので、ご確認よろしくお願いいたします。
- Dictionaryモデルで定義しているメソッドをscope化。目的(対象)はEntryの絞り込みのため、Entryモデルに移動
- Dictionaryモデルで定義している絞り込みメソッドのうち、どこにも使われていないものを削除
- 手動で確認し、問題なく動作することを確認
https://docs.pubdictionaries.org/lookup-api/
今回編集したscopeを使用している`substring_completion`、`prefix_completion`、`mixed_completion`を実行
https://github.com/pubannotation/pubdictionaries/assets/149556430/cac60175-01fd-4de6-9e45-38b897fe19fb

絞り込みメソッドをscope化(lookup)

---

app/models/dictionary.rb

close #104 
類義語自動拡張の対象の変更が完了しましたので、ご確認よろしくお願いいたします。
- `synonym_expansion`関数に通すEntryの対象を`Black以外`→`White or Gray (=activeモード)`に変更
- 手動で、対象モードのEntryのみが自動拡張されることを確認
White + Gray = 7
Auto expanded = 21　→Expand synonym→　28（White + Grayの分だけ拡張されている）
https://github.com/pubannotation/pubdictionaries/assets/149556430/db111f06-ef34-43e8-af0b-8cc4437b6a23

類義語自動拡張の対象をwhite,grayのみに変更

---

app/assets/stylesheets/entries.scss
app/controllers/entries_controller.rb
app/models/dictionary.rb
app/views/entries/_colgroup.erb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb
config/routes.rb

close #105 
類義語のwhite確定を複数一括選択化が完了しましたので、ご確認よろしくお願いいたします。
- 「○にチェック」アイコンの列を削除
- ゴミ箱アイコンの横に「○にチェック」アイコンを設置し、これを押下したらチェックされているEntryを一括でWhiteに確定するように仕様変更
- 同じ領域でForm_tagをputとdeleteで共存できなかったので、scriptでクリックされたボタンに応じてdestroy_entriesかconfirm_to_whiteにsubmit出来るように対応
必要であれば別途対応したいと思います。
- scriptは前の慣習に沿って、jsファイルを作成するのではなくhtml.erb内に記載しました
修正前
修正後
https://github.com/pubannotation/pubdictionaries/assets/149556430/c4be7830-ee0f-45fb-a4df-f93ac30afecb

類義語のwhite確定を複数一括選択化

---

app/controllers/dictionaries_controller.rb
app/models/dictionary.rb
app/views/dictionaries/_form.html.erb
db/migrate/20240314070046_add_associated_annotation_project_to_dictionaries.rb
db/schema.rb

close #107 
Dictionaryへのassociated_annotation_projectカラム追加が完了しましたので、ご確認よろしくお願いいたします。
- Dictionaryテーブルにassociated_annotation_projectカラムを追加
- バリデーションは[PubAnnotationのプロジェクトの名前](https://github.com/pubannotation/pubannotation/blob/1b19484ef01e5b1b3141d4e86e5681c4ba8f3a17/app/models/project.rb#L25-L26)と同じに設定
- Dictionary設定画面(新規、編集)にAssociated Annotation Projectプロパティの入力フォームを追加し、associated_annotation_projectを登録できるように設定
- 入力フォームの説明文言は雰囲気で入力しましたので、確認依頼をお願いいたします。
- 現時点で、登録したassociated_annotation_projectをDictionary詳細画面などに表示するようにはしていません。
- 編集画面の"`License`"のつづりが間違っているところを見つけたので、ついでに直しておきました。
成功するところ
https://github.com/pubannotation/pubdictionaries/assets/149556430/775a9cba-fd1b-4cdb-a25d-123457a4f7b7
バリデーションエラー
https://github.com/pubannotation/pubdictionaries/assets/149556430/ed0bd0e0-c2c9-4e8c-b9eb-4b1 …

Dictionaryにassociated_annotation_projectカラム追加

---

app/controllers/dictionaries_controller.rb
app/models/entry.rb
app/models/tag.rb

close #106 
ActiveとCustomの情報をダウンロードしたときのtsvファイルへのタグ列追加が完了しましたので、ご確認よろしくお願いいたします。
- tag.valueのバリデーションで空白を許可していたのを削除し、エラー時の文言も変更
https://github.com/pubannotation/pubdictionaries/assets/149556430/b96f8436-f969-437f-b201-48e8b1497944
- tag列をidentifierの右に追加し、複数ある場合は'|'区切りで記載するように修正（active, custom両方とも）
- Active
ダウンロードしたファイル(EntrezGene.tsv)の内容
```tsv
#label	id	#tags
Gray Mode Entry	1	Giraffe|Tiger|Elephant
Gray Mode Entry2	2	Giraffe|Elephant
White Mode Entry	1	Giraffe|Tiger|Elephant
White Mode Entry2	2	Elephant
White Mode Entry3	2	""
White Mode Entry4	3	Giraffe|Elephant
White Mode Entry5	4	""
```
- Custom
ダウンロードしたファイル(EntrezGene_custom.tsv)の内容
```tsv
#label	id	#tags	operator
White Mode Entry	1	Giraffe|Tiger|Elephant	+
White Mode Entry2	2	Elephant	+
White Mode Entry3	2	""	+
White Mode Entry4	3 …
```

ActiveとCustomの情報をダウンロードしたときのtsvファイルへのタグ列追加

---

app/views/dictionaries/_form.html.erb
db/seeds.rb

close #120
seedにassociated_annotation_project追加が完了しましたので、ご確認よろしくお願いいたします。
- formにassociated_annotation_projectの項目を追加した際、必須の`*`を記載し忘れていたため、追記
- seedファイルにてDictionaryを作成する箇所にassociated_annotation_projectの設定を追加
問題なくseed実行ができたことを確認

seedにassociated_annotation_project追加

---

app/controllers/dictionaries_controller.rb
app/models/dictionary.rb

close #109 
htmlに合わせたjsonデータ作成が完了しましたので、ご確認よろしくお願いいたします。
1. 過去のcommitの段階で同じエラー(#109 )が起きているか確認　→　起きていた
2. `dics`の部分を`Dictionary.all`にしてみる
　→　indexのhtmlでは`public: :true`のみで表示される内容も絞られているので、不適当と判断
- htmlで表示している条件(`@dictionaries_grid`)と同じDictionaryを抜粋
- それらのnameなど、htmlで表示している項目をマッピングしたJson用データを作成し、`dics`としてjsonに渡す
上：JSON、下：HTML

htmlに合わせたjsonデータ作成

---

app/helpers/entries_helper.rb
app/views/entries/_colgroup.erb
app/views/entries/_entry.html.erb
app/views/entries/_table.html.erb

close #108 
Entry一覧へのPubAnnotationリンク追加が完了しましたので、ご確認よろしくお願いいたします。
- 虫眼鏡の列の右にリンクアイコンを設置し、issueで提示いただいたリンクに遷移するように設定
- リンクにマウスを乗せたときに出てくる文言(title)は虫眼鏡と同じ`search`としています
- base projectの欄に紐づけたproject名が入るはずでしょうか？idはフォームに入力された状態ですが、project名は入力されていない状態で表示されました。（下の画像参照）
リンクを追加したDictionary詳細画面
リンク押下後
- 404ではなく、既存のページ？に飛びました
- base projectの欄に紐づけたproject名が入るはずでしょうか？
`#{entry.identifier}`のところに`bbbbb`、
`#{@dictionary.associated_annotation_project}`のところにこのDictionary
と紐づけた`aaaa_project`
が入っていることを確認
```
https://pubannotation.org/term_search?term_search_controller_query%5Bblock_type%5D=sentence&term_search_controller_query%5Bterms%5D=bbbbb&term_search_controller_query%5Bpredicates%5D=&term_search_controller_query%5Bbase_project%5D=aaaa_project&term_search_controller_query%5Bbase_project%5D=&term_search_cont …
```

Entry一覧へのPubAnnotationリンク追加

---

app/controllers/dictionaries_controller.rb
app/models/dictionary.rb

close #113 
dictionary名を変更したらエラーになる件の対処をしましたので、ご確認よろしくお願いいたします。
デバッグの結果、そのDictionaryに事前に`@dictionary.sim_string_db_dir`が設定されていないことが原因で、以下の流れでエラーになっていました。
```
def update
begin
...
db_loc_old = @dictionary.sim_string_db_dir
if @dictionary.update(dictionary_params)
db_loc_new = @dictionary.sim_string_db_dir
FileUtils.mv db_loc_old, db_loc_new unless db_loc_new == db_loc_old
...
rescue => e
redirect_back fallback_location: @dictionary, notice: e.message
end
end
```
- `Dictionary.name`を変更してDictionary#updateを実行
- `@dictionary.update(dictionary_params)`が成功
- `db_loc_old`が存在しないため、`FileUtils.mv`がエラー
- `resucue→redirect_back`しようとするが、redirect_backしようとしているupdate前のアドレスがない（Dictionary名はすでにupdateした後のため)と判断してエラー
- `FileUtils.mv db_loc_old, db_loc_new`の実行条件として、`db_loc_old`が存在するかの事前確認を追加
- …

dictionary名を変更したらエラーになる件の原因究明と対処

---

README.md

google reCAPTCHAの登録手順をREADMEに追記しました。
内容はPubAnnotationに書いたものとほぼ同じです。
一点だけ変更を加えており、labelの例を`pubannotation`から`pubdictionaries`と、リポジトリに合わせる形にしました。
|<img width="379" alt="image" src="https://github.com/user-attachments/assets/7383abf4-a2c8-4bdc-a5c5-97599530eff2">|
|:-|

google reCAPTCHAの登録手順をREADMEに追記

---

app/controllers/annotation_controller.rb
app/jobs/text_annotation_job.rb

Closes: #131
PubAnnotationのアノテーション獲得プロトコールの改善における、PubDictionaries側の処理を追加しました。
- annotation_controller#annotation_request
- パラメータからコールバックURLを取得し、TextAnnotationJobにコールバックURLを渡すように変更
- アクション自体のHTTP返答は303 see otherから200 okに変更
- ログに`Can't verify CSRF token authenticity.`が出ていたので、annotation_taskアクションと同様にCSRFチェックを無効化
- TextAnnotationJob
- コールバックURLがある場合はそのURLにアノテーション結果をPOSTする処理を追加
従来のアノテーション結果です
callbackURLへPOSTしたアノテーション結果です。従来のものと一致していることが確認できます。

アノテーションが終わるとコールバックURLに結果をPOSTする機構を追加

---

app/jobs/text_annotation_job.rb

コールバックURLへのリクエストをPOSTからPUTに変更しました。
- コールバックURLへのリクエストをPOSTからPUTに変更
- アノテーション結果は必ず配列として返すように変更
PUTリクエストの確認と結果が配列になっていることを確認しました。
PubAnnotation側

コールバックURLへのリクエスト修正

---

app/controllers/application_controller.rb
app/controllers/concerns/recaptchable.rb
app/controllers/users/passwords_controller.rb
app/controllers/users/registrations_controller.rb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb

Recaptcha環境変数を設定していない場合に機能を無効化しました。
- recaptcha環境変数が設定されていない場合に、以下の機能を無効化
- viewでの表示
- controllerでの認証
|<img width="463" alt="image" src="https://github.com/user-attachments/assets/256d50b5-9597-4f15-8b9e-429ba7d6a7ef">|
|:-|
リダイレクト
|<img width="1030" alt="image" src="https://github.com/user-attachments/assets/3ddfe69e-fec3-4aea-bc40-1431f8d00a3d">|
|:-|
|<img width="836" alt="image" src="https://github.com/user-attachments/assets/6b138cbc-bfbb-4104-b47d-560a6c9095c7">|
|:-|
リダイレクト
|<img width="699" alt="image" src="https://github.com/user-attachments/assets/38218b7a-4fbb-4ba4-8093-2e8eacfa3bcf">|
|:-|
|<img width="585" alt="image" src="https://github.com/user-attachments/assets/0a1511d6-ef82-4764-a660-0e7de39ad2a7">|
|:-|

Recaptcha環境変数を設定していない場合に機能を無効化

---

app/controllers/annotation_controller.rb

PubAnnotation側でリクエストへのコールバックURL添付方法が変わったため、それに合わせてPubDictionaries側のURL摘出方法を変更しました。

コールバックURLの摘出方法を修正

---

app/controllers/api/v1/entries_controller.rb
app/jobs/load_entries_from_file_job.rb
app/lib/exceptions.rb
app/models/dictionary.rb
config/routes.rb

Closes: #138
以下の実装を行いました。
- 辞書のエントリーの追加、削除、元に戻し等の操作をAPIでできるようにする。
- POSTによる辞書のバルクアップロードをAPIでできるようにする。
- 以下機能のAPIを作成
- エントリー追加 Api::V1::EntriesController#create
- エントリー削除 Api::V1::EntriesController#destroy_entries
- エントリー元に戻し Api::V1::EntriesController#undo
- 辞書のバルクアップロード Api::V1::EntriesController#upload_tsv
- 各ルーティングを設定
認証実装前の動作確認のために、全てのAPIに `current_user = User.first`を定義して行います。
この辞書の状態から動作確認します。
|<img width="1069" alt="image" src="https://github.com/user-attachments/assets/67d35532-f623-48d0-89bb-89e00efdcc8b">|
|:-|
```
curl -X POST http://localhost:3001/api/v1/entries \
-H "Content-Type: application/json" \
-d '{
"dictionary_id": "EntrezGene",
"label": "test-with-api-call",
"identifier": "1"
}'
{"message":"The white entry ('test-with-api-call', '1') was created."}%
```
|<img …

辞書のエントリー操作・バルクアップロードAPIを作成

---

app/controllers/api/v1/entries_controller.rb
app/controllers/entries_controller.rb
app/models/dictionary.rb
app/models/entry.rb
db/seeds.rb

Closes: #140 
[issue](https://github.com/pubannotation/pubdictionaries/issues/140)に基づいてエントリー数更新をコールバックで行う形に変更しました。
Entryモデルにエントリー数更新のコールバックを追加
コールバック追加により以下メソッドのエントリー更新処理を削除
- after_save関連
- EntriesController#create
- api/v1/EntriesController#create
- Dictionary#append_expanded_synonym_entries
- seeds
- after_destroy関連
- EntriesController#destroy_entries
- api/v1/EntriesController#destroy_entries
- Dictionary#undo_entry
- Dictionary#empty_entries
上記タイミングの他に、エントリーの色が変わるタイミングで`update_entries_num`を呼び出すことがあります。
Gray→Black, Black→Grayなどのタイミングでは`update_entries_num`を呼び出していて、Gray→Whiteのタイミングでは`update_entries_num`は呼び出していません。
after_updateを用いれば色変更のタイミングでも明示的に`update_entries_num`を書かずに更新できますが、Gray→Whiteのような不要なタイミングでも実行されるようになってしまうので実装しませんでした。 …

エントリー数更新をコールバックで行う形に変更

---

app/controllers/api/v1/entries_controller.rb
app/controllers/api/v1/jobs_controller.rb
config/routes.rb

Closes: #143
既存ジョブが残っているとジョブを作成するAPIが実行できない問題への対応として、
ジョブをAPIで削除する機能を追加しました。
コードレビューに加えて、以下の点についても確認をお願いしたいです。
- ジョブを消すAPIの案内メッセージなどの文言が問題ないか
- オプションはクエリパラメータで実装したが問題ないか
- オプション名は問題ないか
- ジョブ削除APIの追加
- ジョブがあるときにジョブを追加したらジョブのメッセージを返すとともに、消すAPIを案内するメッセージを添付
- ジョブ追加するAPIに、終了済みのジョブを強制的に消すオプションを追加
```
curl -X DELETE http://localhost:3001/api/v1/jobs/4f196da6-d550-431c-9219-1d7d50891bba
{"message":"Job 4f196da6-d550-431c-9219-1d7d50891bba was successfully deleted."}%
```
ログ
ジョブがある状態でジョブを作成するAPIを実行
```
curl -X POST http://localhost:3001/api/v1/entries/tsv \
-H "Content-Type: multipart/form-data" \
-F "dictionary_id=EntrezGene" \
-F "file=@test.tsv"
{"error":"The last task is not yet dismissed. Please dismiss it and try again.","task_dismiss_instruction":"To dismiss the task, send a DELETE request …
```

JobをAPIで削除する機能を追加

---

app/controllers/api/v1/entries_controller.rb

Job削除オプション名を`force`に変更しました。
- api/v1/entries_controller#upload_tsvのJob削除オプション名を`replace_task`から`force`に変更
連続して実行しても問題なくAPIが実行できることを確認しました。
```
curl -X POST "http://localhost:3001/api/v1/entries/tsv?force=true" \
-H "Content-Type: multipart/form-data" \
-F "dictionary_id=EntrezGene" \
-F "file=@test.tsv"
{"message":"Upload dictionary entries task was successfully created."}%
curl -X POST "http://localhost:3001/api/v1/entries/tsv?force=true" \
-H "Content-Type: multipart/form-data" \
-F "dictionary_id=EntrezGene" \
-F "file=@test.tsv"
{"message":"Upload dictionary entries task was successfully created."}%
```

Jobを生成するAPIのJob削除オプション名を変更

---

app/assets/stylesheets/user.scss
app/controllers/access_tokens_controller.rb
app/controllers/api/v1/entries_controller.rb
app/controllers/users_controller.rb
app/models/access_token.rb
app/models/user.rb
app/views/users/show.html.erb
config/initializers/client_credential_flow.rb
config/routes.rb
db/migrate/20240905071740_create_access_tokens.rb
db/migrate/20240910064916_remove_expired_at_from_access_tokens.rb
db/schema.rb

Closes: #145
アクセストークンの寿命や関連を修正しました。
- トークン寿命が無くなったためAccessTokenテーブルから`expired_at`カラムを削除
- トークン寿命に関するロジック, メッセージを削除
- ユーザーとアクセストークンを1対1の関係に修正
- トークン削除機能を作成
- ユーザーがトークンを持っている場合、生成ボタンは押下不可に変更
`expired_at`の削除はAccessTokenテーブル作成のmigrationファイルをロールバックして直接修正しましたが、別でmigrationファイルを作った方がよかったでしょうか？確認お願いします :pray:
|<img width="1144" alt="image" src="https://github.com/user-attachments/assets/7a6822a6-0bb6-4839-a64c-f078d989b188">|
|:-|
トークンが表示され、生成ボタンは押せなくなります。
|<img width="1056" alt="image" src="https://github.com/user-attachments/assets/6cc3b493-7a51-486a-bb80-8ee56e4ee08f">|
|:-|
ゴミ箱ボタンから削除可能です。
|<img width="1205" alt="image" src="https://github.com/user-attachments/assets/a1f451d0-36f3-43f4-aa8e-ffa52cada51e">|
|:-|
|<img width="1112" alt="image" …

アクセストークンの寿命や関連を修正

---

app/jobs/load_entries_from_file_job.rb

Closes: #148 
バルクアップロードの際に速度向上のためバリデーションを省略し、改善を行いました。
- BufferToStore#buffer_entryでエントリーがすでにあるかどうかのチェックを削除
- LoadEntriesFromFileJobを辞書が空の場合にのみ実行可能に変更
辞書が空の場合でJobを実行します。
|<img width="1089" alt="image" src="https://github.com/user-attachments/assets/6f4f9bf3-d85c-4b1e-8f77-1270a2a2a16b">|
|:-|
正常に動作します。
|<img width="777" alt="image" src="https://github.com/user-attachments/assets/b025b846-b55f-4166-b845-6f7b254525c2">|
|:-|
|<img width="1128" alt="image" src="https://github.com/user-attachments/assets/a1ef89d8-f347-4aef-883e-783e4afb819e">|
|:-|
失敗するとともにメッセージが表示されます。
|<img width="754" alt="image" src="https://github.com/user-attachments/assets/79f31cd8-338a-422e-b39a-b817f0a0e3d8">|
|:-|
約60エントリーをバルクアップロードした結果です。
手動で検証したので信頼性はあまりないかもですが、パフォーマンスは良くなったように思えます。
```
改善前
1回目：427.29ms …
```

バルクアップロードの際に速度向上のためバリデーションを省略

---

app/controllers/api/v1/entries_controller.rb
app/models/dictionary.rb

Closes: #151
Jobの実行中はAPIからのエントリー操作を不可能に修正しました。
バルクアップロードJobの実行中は既存のエントリーは空なため、エントリー作成APIだけでなく全てのエントリー操作APIを失敗させるように修正を加えました。
- Jobが進行中の場合、その旨のエラーメッセージを返すメソッドをAPIのbefore_actionとして設定
```
curl -X POST http://localhost:3001/api/v1/entries \
-H "Content-Type: application/json" \
-H "Authorization: Bearer a26fcb5f299d37e7c1f41d6eb0def1e0" \
-d '{
"dictionary_id": "EntrezGene",
"label": "test-with-api-call",
"identifier": "1"
}'
{"error":"The last task is still in progress. Please wait a moment and try again later."}%
```
```
curl -X POST http://localhost:3001/api/v1/entries/tsv \
-H "Content-Type: multipart/form-data" \
-H "Authorization: Bearer a26fcb5f299d37e7c1f41d6eb0def1e0" \
-F "dictionary_id=EntrezGene" \
-F "file=@test.tsv"
{"error":"The last task is still in progress. Please wait a …
```

Jobの実行中はAPIからのエントリー操作を不可能に修正

---

app/models/dictionary.rb
app/models/entry.rb

Closes: #154 
バルクアップロードの速度向上の為の最適化を実施しました。
- Elasticsearchへの問い合わせをラベル単位からバッチ単位でまとめて行うように変更
使用データ
```
microfold cell of epithelium proper of appendix	id1	tag1
uterine cervix	id2	tag2|tag3
islet of Langerhans	id3	tag3
submucosa	id4	tag4
```
```
[#<Entry:0x00007ffff5b1ee58
id: 73639,
mode: 0,
label: "microfold cell of epithelium proper of appendix",
norm1: "microfoldcellofepitheliumproperofappendix",
norm2: "microfoldcellepitheliumproperappendix",
label_length: 47,
identifier: "id1",
dictionary_id: 1,
created_at: Wed, 18 Sep 2024 02:19:09.757828000 UTC +00:00,
updated_at: Wed, 18 Sep 2024 02:19:09.757828000 UTC +00:00,
dirty: false,
score: nil>,
#<Entry:0x00007ffff7124f68
id: 73640,
mode: 0,
label: "uterine cervix",
norm1: "uterinecervix",
norm2: "uterincervix",
label_length: 14,
identifier: …
```

バルクアップロードの速度向上の為の最適化を実施

---

app/models/entry.rb

normalize処理においてDBに保存する`norm1`, `norm2`の値を正しく構成できていない問題があり、この問題を修正しました。
Elasticsearchが返すレスポンス内の`position`キーの値が101ではない場合は同一ラベルという判断をしていました。
ただ、ラベルの前後に`of`などのnormalize処理によって省略される値がある場合、`position`キーの値が101以上になります。
この場合に同一ラベルの判断に不具合が生じていたので、判断内容を
"差が101じゃない場合は同一ラベル"
から
"差が101より少ない場合、同一ラベル"
と変更することで不具合に対応しました。
使用データ
```
appendix of	id1	tag1
uterine cervix	id2	tag2|tag3
of islet of Langerhans	id3	tag3
submucosa	id4	tag4
```
```
[#<Entry:0x00007ffff6d84cf0
id: 143687,
mode: 0,
label: "appendix of",
norm1: "appendixof",
norm2: "appendixuterincervixisletlangerhan",
label_length: 11,
identifier: "id1",
dictionary_id: 1,
created_at: Wed, 18 Sep 2024 07:08:33.454664000 UTC +00:00,
updated_at: Wed, 18 Sep 2024 07:08:33.454664000 UTC +00:00,
dirty: false,
score: nil>,
#<Entry:0x00007ffff716be68
id: …
```

演算子によるnormalize処理の不具合を修正

---

app/controllers/entries_controller.rb
app/jobs/load_entries_from_file_job.rb
app/models/analyzer.rb
app/models/dictionary.rb
app/models/entry.rb

normalize関連の処理をリファクタリングしました。
- Analyzerクラスの作成
- Entryモデルのnormalize処理をAnalyzerクラスに移動
- その他引数名の改善など
Analyzer#normalizeと変更を加えたエントリー作成周りの処理が動作することを確認
|<img width="1033" alt="image" src="https://github.com/user-attachments/assets/42327a3d-b887-4622-a9aa-581a3f39e4bf">|
|:-|
Analyzer#batch_normalizeと変更を加えたバルクアップロード周りの処理が動作することを確認
```
abc def	id1
of	id2
hig	id3
```
(※ progressが3/5になっているのはローカルでバルクアップロードを行うために追加した設定のせいです)
|<img width="705" alt="image" src="https://github.com/user-attachments/assets/583d07e3-2bad-4759-a59e-65b6de42d1cf">|
|:-|
|<img width="1048" alt="image" src="https://github.com/user-attachments/assets/f189f459-69b2-4a77-9f43-ef3049d8bcb1">|
|:-|
```
[#<Entry:0x00007ffff6e5d230
id: 153896,
mode: 0,
label: "abc def",
norm1: "abcdef",
norm2: "abcdef",
label_length: 7,
identifier: …
```

normalize関連の処理をリファクタリング

---

app/models/dictionary.rb

CloneDictionaryJobの削除によってDictionary#add_entriesの呼び出しもとが1つとなり、デフォルト引数を使用するルートがなくなったためデフォルト引数を削除しました。

不要なデフォルト引数の設定を削除

---

app/controllers/entries_controller.rb
app/jobs/load_entries_from_file_job.rb
app/jobs/load_entries_from_file_job/buffer_to_store.rb
app/models/analyzer.rb
app/models/dictionary.rb

エントリー処理周りのリファクタリングを行いました。
- Dictionary#new_entryのデフォルト引数をローカル変数に変更
- https://github.com/pubannotation/pubdictionaries/pull/160/commits/302a63b1106e76ee0cac5ba28868db7d74454d35
- LoadEntriesFromFileJob::BufferToStoreを別ファイルに移動
- https://github.com/pubannotation/pubdictionaries/pull/160/commits/3593cc856af8dc8724e0a8f580633a696c58e2eb
- BufferToStoreクラス内でanalyzerの初期化、呼び出し、解放を完結するように変更
- https://github.com/pubannotation/pubdictionaries/pull/160/commits/4e1e7d58d02df22221db80400ee67fec7a8a0ee8
|<img width="1087" alt="image" src="https://github.com/user-attachments/assets/f15243a8-719e-4ffe-85f1-bc5ec4f76352">|
|:-|
ログ
|<img width="484" alt="image" src="https://github.com/user-attachments/assets/361d33a6-8895-4317-8861-67077dc173df">|
|:-|
|<img width="1069" alt="image" …

エントリー処理周りのリファクタリング

---

app/jobs/load_entries_from_file_job.rb
app/jobs/load_entries_from_file_job/buffer_to_store.rb
app/models/analyzer.rb
app/models/batch_analyzer.rb

LoadEntriesFromFileJob周りのリファクタリングを行いました。
- Analyzerクラスを単発用とバッチ用で分割
- https://github.com/pubannotation/pubdictionaries/pull/161/commits/01da4ec374da80f8f43ce2fa4185185f80a591ac
- BufferToStore内のパターン関連のコードを削除
- https://github.com/pubannotation/pubdictionaries/pull/161/commits/4848a45880554ed8b869cce981171bac59a1add0
- LoadEntriesFromFileJob#performで例外で抜けた時もtmpファイルが削除されるように変更
- https://github.com/pubannotation/pubdictionaries/pull/161/commits/d09e5352130aa008a69430cea4aae33927e69bae
- LoadEntriesFromFileJob#performでファイルの事前処理を外部コマンドからRubyに変更
- https://github.com/pubannotation/pubdictionaries/pull/161/commits/a6bacf1d3c757ae66062c671a8ac44d23d78eb17
|<img width="1072" alt="image" src="https://github.com/user-attachments/assets/6e056ade-0432-4cdb-a8ab-3c4d84ad9aea">|
|:-|
ログ
|<img width="493" …

LoadEntriesFromFileJob周りのリファクタリング

---

app/jobs/load_entries_from_file_job.rb
app/jobs/load_entries_from_file_job/buffer_to_store.rb
app/models/batch_analyzer.rb
app/models/dictionary.rb

指定された内容のリファクタリングを行いました。
- 使用されていないメソッドの削除 (Dictionary.normalize2)
- https://github.com/pubannotation/pubdictionaries/commit/7dae299ac82ec5fb9e9ab849c00ef74d0d1f8907
- 不要な&演算子の削除
- https://github.com/pubannotation/pubdictionaries/commit/a0192871f6268911b12aaefc4fb9c48caf6dd404
- BufferToStore#flush_entriesのリファクタリング
- https://github.com/pubannotation/pubdictionaries/commit/07485bfb358e9f91e83a092c412c1ed99ad7f51b
- LoadEntriesFromFileJob#perform内の不要な`nil`チェックを削除
- https://github.com/pubannotation/pubdictionaries/commit/36f9da4f7f9f0828186ea6f29b40385d2f604bbb
- エラー処理を例外に変更
- https://github.com/pubannotation/pubdictionaries/commit/fc4d87b411bee5689138b4490821e39840d430e1
|<img width="481" alt="image" src="https://github.com/user-attachments/assets/bdaa4588-5177-4089-837e-9cf2df5df7c3">|
|:-| …

細かい点をリファクタリング

---

app/models/batch_analyzer.rb

バルクアップロード処理において、最後のラベルが全スキップされるとnorm2の最後が期待する`""`ではなく`nil`になってしまう問題がありました。
この問題を修正しました。
- BatchAnalyzer#normalizeに、数が足りない分を""で埋める処理を追加
```
abc def	id1
hig	id2
of	id3
of of	id4
```
```
irb(main):001> Dictionary.first.entries
Dictionary Load (2.2ms)  SELECT "dictionaries".* FROM "dictionaries" ORDER BY "dictionaries"."id" ASC LIMIT $1  [["LIMIT", 1]]
Entry Load (0.7ms)  SELECT "entries".* FROM "entries" WHERE "entries"."dictionary_id" = $1  [["dictionary_id", 1]]
=>
[#<Entry:0x00007ffff5770a68
id: 1655909,
mode: 0,
label: "abc def",
norm1: "abcdef",
norm2: "abcdef",
label_length: 7,
identifier: "id1",
dictionary_id: 1,
created_at: Fri, 27 Sep 2024 02:58:05.374392000 UTC +00:00,
updated_at: Fri, 27 Sep 2024 02:58:05.374392000 UTC +00:00,
dirty: false,
score: nil>,
#<Entry:0x00007ffff75baaa0 …
```

バルクアップロード処理のnormalize不具合を修正

---

app/jobs/load_entries_from_file_job.rb
app/jobs/load_entries_from_file_job/flood_gate.rb

エントリー毎に行われていたJobの進捗更新を、バッファに対応する形に変更しました。
- BufferToStoreクラスをFloodGateクラスに命名変更
- Jobの進捗更新をバッファに対応する形に変更
Progressの分子がバッファサイズ単位で更新されるようになりました。
|<img width="454" alt="image" src="https://github.com/user-attachments/assets/468037f8-f93f-4107-88a8-a0a274196d90">|
|:-|
最後に残った数の処理も問題なく反映されています。
|<img width="555" alt="image" src="https://github.com/user-attachments/assets/1c457636-bb63-41da-a954-3589b841c119">|
|:-|
|<img width="500" alt="image" src="https://github.com/user-attachments/assets/5f058c3b-3260-43cb-a59e-c71ea149205c">|
|:-|

Jobの進捗更新をバッファに対応する形に変更

---

app/jobs/load_entries_from_file_job.rb
app/jobs/load_entries_from_file_job/flood_gate.rb

バルクアップロード機能において、Job中断機能が大量のSQLを発行していました。
バッファ単位でSQLを発行するように変更し、実行速度の向上を行いました。
|<img width="490" alt="image" src="https://github.com/user-attachments/assets/70cdda8c-d25c-4881-b52d-83208dcf3b4f">|
|:-|
|<img width="396" alt="image" src="https://github.com/user-attachments/assets/0ae1f5d1-a5a1-4268-8e38-a1bf2a31f9e7">|
|:-|
|<img width="446" alt="image" src="https://github.com/user-attachments/assets/3f755b37-34f8-4fa2-baff-1d08d6f4b94d">|
|:-|

バルクアップロードのSQL改善

---

app/jobs/load_entries_from_file_job.rb

LoadEntriesFromFileJob内の`dictionary.compile!`処理を削除しました。

仕様に合わせて不要になったコンパイル処理を削除

---

config/environments/development.rb
config/environments/production.rb

RailsのurlヘルパーがフルURLを生成する時に、以下の箇所でArgumentErrorエラーが発生していました。
https://github.com/pubannotation/pubdictionaries/blob/67d89677a4d771a68726a5b62cde486ff65f70ee/app/models/job.rb#L38
エラー内容
`ArgumentError (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):`
このエラーによって、ポーリング処理を行うPubAnnotationのAutomatic annotation機能でエラーが発生していました。
対応として、エラーメッセージに従って`default_url_options`を設定することで解決しました。
- development.rb/production.rbにそれぞれdefault_url_optionsを設定
現状default_url_optionsを使用するテストは無かったため、test.rbへの追加は行いませんでした。
(他に合わせて追加すべきであれば追加します。)
```
(ruby) status[:result_location]
"http://localhost:3001/annotation_results/annotation-791c9522-6f5d-448a-8be6-16937674960c.json"
```
|<img width="379" alt="image" …

ヘルパーによるURL組み立てエラーを修正

---

config/environments/production.rb
config/environments/test.rb

Railsバージョンアップによって変更された環境設定ファイルに不具合があったため、修正しました。
- config.assume_ssl設定のコメントアウト
- config.action_mailer.default_url_optionsを正しく設定
production環境でdeviseが送るメールをクリックすると、デプロイ先のサーバーにリクエストが送信されることを確認しました。

Fix environment settings changed by rails update

---

config/elasticsearch.yml
test/controllers/api/v1/entries_controller_test.rb
test/fixtures/dictionaries.yml
test/fixtures/entries.yml
test/fixtures/files/sample_tsv_entries.tsv
test/fixtures/users.yml

Entry APIにテストを追加しました。
- テストの追加
- 各APIの正常系の確認
- 各APIの異常系の確認
- Client Credential認証の確認
- dockerでテスト環境時にElasticsearchに接続できるようにelasticsearch.ymlに設定を追加
テストが2回実行されていますが、既存のテストが上の8testのもので、追加したテストは下のものです。
```
docker compose exec web rails test
Loaded suite bin/rails
Started
Finished in 0.014012375 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
8 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```

Add entry API test

---

app/controllers/api/v1/entries_controller.rb

Entry undo APIで指定のEntryが見つからない場合の例外処理が正しく行われていない問題を修正しました。
期待するレスポンスが返ることを確認しました。
```
curl -X PUT http://localhost:3000/api/v1/entries/123/undo \
-H "Authorization: Bearer 4009b610fe42472dda6ab8e49d1704d8" \
-H "Content-Type: application/json" \
-d '{
"dictionary_id": "EntrezGene"
}'
{"error":"Cannot find the entry."}%
```

Fix entry undo API error handling

---

app/controllers/api/v1/entries_controller.rb
test/controllers/api/v1/entries_controller_test.rb

Entry undo APIで指定したIDが見つからなかった場合に400 bad requestが返っていました。
リクエストされたリソースを見つけることができない場合は404 not foundの方が適しているため、404を返すように修正しました。
```
docker compose exec web rails test
Loaded suite bin/rails
Started
Finished in 0.013593084 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
8 tests, 8 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
588.53 tests/s, 588.53 assertions/s
Run …
```

Fix entry undo API error response code

---

Dockerfile
compose.yml

Dockerでサーバーが起動できない問題を修正しました。
- DockerfileのRuby versionを更新
- Docker内でPostgreSQL vector拡張機能に対応しているDBを使用するように変更
サーバーが起動できることを確認
```
web-1            | => Booting WEBrick
web-1            | => Rails 8.0.1 application starting in development http://0.0.0.0:3000
web-1            | => Run `bin/rails server --help` for more startup options
web-1            | [2025-03-25 02:36:52] INFO  WEBrick 1.9.1
web-1            | [2025-03-25 02:36:52] INFO  ruby 3.4.2 (2025-02-15) [x86_64-linux]
web-1            | [2025-03-25 02:36:52] INFO  WEBrick::HTTPServer#start: pid=19 port=3000
```

Fix cannot start server in docker
